import React, { useState, useEffect } from 'react';
// Imports from YOUR ORIGINAL HairScan + Loader2
import { Camera, User, Baby, Sun, X, Sparkles, Download, History, Loader2 } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { uploadToCloudinary } from './cloudinary';
import { saveHairAnalysis } from './firestoreService';
import { auth } from './firebase';
import { onAuthStateChanged } from 'firebase/auth';



// The main component for the hair scan upload page.
const HairScan = () => {
  const navigate = useNavigate();
  const [age, setAge] = useState('');
  const [gender, setGender] = useState('');
  const [hairType, setHairType] = useState('');
  const [file, setFile] = useState(null);
  const [preview, setPreview] = useState(null);
  const [message, setMessage] = useState({ text: '', type: '' });
  const [isLoaded, setIsLoaded] = useState(false);
  const [analysisResult, setAnalysisResult] = useState(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [currentUser, setCurrentUser] = useState(null);
  const [uploadingToCloudinary, setUploadingToCloudinary] = useState(false);
  const [currentAnalysisId, setCurrentAnalysisId] = useState(null);

  useEffect(() => {
    setIsLoaded(true);
    const unsubscribe = onAuthStateChanged(auth, (user) => {
      setCurrentUser(user);
    });
    return () => unsubscribe();
  }, []);



  const showMessage = (text, type) => {
    setMessage({ text, type });
    setTimeout(() => {
      setMessage({ text: '', type: '' });
    }, 3000);
  };

  const removePhoto = () => {
    setFile(null);
    if (preview) {
      URL.revokeObjectURL(preview);
    }
    setPreview(null);
    showMessage('Photo removed successfully', 'success');
  };

  const handleAgeChange = (e) => {
    const value = e.target.value;
    if (value === '' || (parseInt(value) >= 1 && parseInt(value) <= 120)) {
      setAge(value);
    } else if (parseInt(value) < 1) {
      showMessage('Age must be at least 1 year', 'error');
    }
  };

  const handleFileChange = (event) => {
    const selectedFile = event.target.files[0];
    if (selectedFile) {
      setFile(selectedFile);
      setPreview(URL.createObjectURL(selectedFile));
      showMessage('Photo uploaded successfully!', 'success');
    }
  };

  const fileToBase64 = (file) => {
    return new Promise((resolve, reject) => {
      const reader = new window.FileReader();
      reader.onload = () => resolve(reader.result.split(',')[1]);
      reader.onerror = reject;
      reader.readAsDataURL(file);
    });
  };

  const downloadAnalysis = () => {
    if (!analysisResult) return;

    const analysisText = `
HAIR ANALYSIS REPORT
=====================

User Information:
- Age: ${age}
- Gender: ${gender}
- Hair Type: ${hairType}
- Analysis Date: ${new Date().toLocaleDateString()}

AI Analysis Results:
${analysisResult}

Generated by Glownexa Hair Analysis AI
    `;

    const blob = new Blob([analysisText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `hair-analysis-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    showMessage('Analysis downloaded successfully!', 'success');
  };


  const resetForm = () => {
    setAge(''); setGender(''); setHairType(''); setFile(null);
    if (preview) { URL.revokeObjectURL(preview); }
    setPreview(null); setAnalysisResult(null); setCurrentAnalysisId(null);
    showMessage('Form reset successfully', 'success');
  };

  const analyzeWithAI = async (imageBase64) => {
    try {
      setIsAnalyzing(true);

      const API_KEY = process.env.REACT_APP_GEMINI_API_KEY;

      const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${API_KEY}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          contents: [{
            parts: [
              {
                text: `As a professional trichologist and hair analysis AI assistant, please analyze this hair image for a ${age}-year-old ${gender} with ${hairType} hair type. Provide a comprehensive analysis including:

HAIR CONDITION ASSESSMENT:
- Overall hair health and condition
- Hair texture and thickness
- Scalp condition visibility
- Hair density and coverage

POTENTIAL ISSUES IDENTIFIED:
- Hair loss or thinning patterns
- Scalp conditions (dryness, oiliness, dandruff)
- Hair damage (breakage, split ends, dryness)
- Any signs of hair disorders

HAIR CARE RECOMMENDATIONS:
- Suitable shampoo and conditioner types
- Hair treatments and masks
- Styling recommendations
- Products to avoid

LIFESTYLE AND NUTRITION TIPS:
- Dietary recommendations for hair health
- Vitamins and supplements if needed
- Hair care routine suggestions
- Environmental protection tips

WHEN TO CONSULT A SPECIALIST:
- Signs that require professional help
- Dermatologist or trichologist consultation

Please provide practical, actionable advice. Be thorough but easy to understand. Focus on the specific hair type: ${hairType}.`
              },
              {
                inline_data: {
                  mime_type: "image/jpeg",
                  data: imageBase64
                }
              }
            ]
          }]
        })
      });

      if (!response.ok) {
        const errorText = await response.text();
        console.error('API Error response:', errorText);

        if (response.status === 429) {
          throw new Error('API quota exceeded. Please try again later.');
        } else if (response.status === 403) {
          throw new Error('API access denied. Please check your API key.');
        } else {
          throw new Error(`HTTP error! status: ${response.status} - ${errorText}`);
        }
      }

      const data = await response.json();

      if (data.candidates && data.candidates[0] && data.candidates[0].content) {
        const resultText = data.candidates[0].content.parts[0].text;
        setAnalysisResult(resultText);
        return resultText;
      } else {
        console.error('Invalid API response format:', data);
        throw new Error('Invalid response format from AI service');
      }
    } catch (error) {
      console.error('Error analyzing with AI:', error);
      setAnalysisResult(null);
      throw error;
    } finally {
      setIsAnalyzing(false);
    }
  };

  const handleSubmit = async (event) => {
    event.preventDefault();
    if (!file) { showMessage('Please upload...', 'error'); return; }
    if (!age || !gender || !hairType) { showMessage('Please fill in...', 'error'); return; }
    if (parseInt(age) < 1) { showMessage('Age must be...', 'error'); return; }
    if (!currentUser) { showMessage('Please log in...', 'error'); return; }
    setIsAnalyzing(true); setAnalysisResult(null); setCurrentAnalysisId(null); setUploadingToCloudinary(false);
    try {
      setUploadingToCloudinary(true); showMessage('Uploading image...', 'info');
      const cloudinaryResult = await uploadToCloudinary(file);
      if (!cloudinaryResult || !cloudinaryResult.success) { console.error("Cloudinary upload failed:", cloudinaryResult?.error); throw new Error(`Cloudinary upload failed: ${cloudinaryResult?.error?.message || cloudinaryResult?.error || 'Unknown error'}`); }
      setUploadingToCloudinary(false);
      showMessage('Image uploaded! Analyzing...', 'info');
      const base64Image = await fileToBase64(file);
      const aiResultText = await analyzeWithAI(base64Image);
      setAnalysisResult(aiResultText);
      showMessage('AI analysis complete! Saving...', 'success');
      const analysisData = { age: parseInt(age), gender: gender, hairType: hairType, originalFileName: file.name, cloudinaryUrl: cloudinaryResult.url, cloudinaryPublicId: cloudinaryResult.public_id, aiAnalysis: aiResultText };
      const saveResult = await saveHairAnalysis(currentUser.uid, analysisData);
      if (saveResult.success) { setCurrentAnalysisId(saveResult.analysisId); showMessage('Hair analysis saved!', 'success'); }
      else { console.error('Failed to save analysis:', saveResult.error); showMessage('Analysis complete, but failed to save...', 'warning'); }
    } catch (error) {
      console.error('Error during hair analysis process:', error); setAnalysisResult(null);
      if (error.message.includes('quota')) { showMessage('API quota exceeded...', 'error'); }
      else if (error.message.includes('Cloudinary')) { showMessage(`Image upload failed: ${error.message}`, 'error'); }
      else if (error.message.includes('API') || error.message.includes('blocked') || error.message.includes('stopped') || error.message.includes('Invalid response format')) { showMessage(`Failed to analyze hair: ${error.message}`, 'error'); }
      else { showMessage(`An unexpected error occurred: ${error.message}`, 'error'); }
    } finally { setIsAnalyzing(false); setUploadingToCloudinary(false); }
  };


 
  return (

    <div className="min-h-screen bg-gradient-to-br from-amber-50 via-orange-50 to-red-100">

      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-20 left-10 w-32 h-32 bg-orange-200/20 rounded-full blur-3xl animate-float"></div>
        <div className="absolute top-40 right-20 w-40 h-40 bg-red-200/20 rounded-full blur-3xl animate-float-reverse"></div>
        <div className="absolute bottom-20 left-32 w-36 h-36 bg-amber-200/20 rounded-full blur-3xl animate-float-slow"></div>
        <Sparkles className="absolute top-32 right-1/4 h-6 w-6 text-orange-300/40 animate-pulse" />
        <Sparkles className="absolute bottom-1/3 left-1/4 h-5 w-5 text-red-300/40 animate-pulse animation-delay-1000" />
      </div>

      <div className={`relative z-10 min-h-screen p-6 flex items-start justify-center transition-all duration-1000 ${isLoaded ? 'opacity-100' : 'opacity-0'}`}>
        <div className="w-full max-w-7xl">
          {/* Header */}
          <div className="text-center mb-8 pt-6">
            <h1 className="text-5xl font-bold bg-gradient-to-r from-amber-600 via-pink-600 to-red-600 bg-clip-text text-transparent mb-3">
              Upload Your Hair Scan
            </h1>
            <p className="text-gray-600 text-lg">
              AI-powered hair health assessment & recommendations
            </p>
          </div>

          {/* Message Box */}
          {message.text && (
            <div className="max-w-3xl mx-auto mb-6">
              <div className={` p-4 rounded-xl shadow-lg text-center font-medium transition-all duration-500 ${message.type === 'success' ? 'bg-green-100 text-green-800 border border-green-200' :
                  message.type === 'error' ? 'bg-red-100 text-red-800 border border-red-200' :
                    message.type === 'info' ? 'bg-blue-100 text-blue-800 border border-blue-200' :
                      'bg-yellow-100 text-yellow-800 border border-yellow-200'
                }`}>
                {message.text}
              </div>
            </div>
          )}

          {/* Conditional Grid Layout */}
          <div className={`grid ${analysisResult ? 'lg:grid-cols-2' : 'lg:grid-cols-1 max-w-3xl mx-auto'} gap-6`}>

            {/* Left Side - Input Form */}
            <div className="bg-white rounded-3xl shadow-xl p-8 border border-gray-100">
              <form onSubmit={handleSubmit} className="space-y-6">
                {/* User Details Section */}
                <div>
                  <h2 className="text-xl font-bold text-gray-800 flex items-center space-x-2 mb-4">
                    <User className="h-5 w-5 text-pink-600" />
                    <span>Personal Information</span>
                  </h2>
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                    {/* Input fields...  */}
                    {/* Age Input */}
                    <div className="space-y-2">
                      <label className="flex items-center space-x-2 text-sm font-semibold text-gray-700">
                        <Baby className="h-4 w-4 text-pink-600" />
                        <span>Age</span>
                      </label>
                      <input type="number" placeholder="e.g., 30" value={age} onChange={handleAgeChange} min="1" max="120" className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-pink-400 focus:border-transparent transition-all bg-gray-50 hover:bg-gray-100 text-gray-800 placeholder-gray-400" required />
                    </div>
                    {/* Gender Selection */}
                    <div className="space-y-2">
                      <label className="flex items-center space-x-2 text-sm font-semibold text-gray-700">
                        <User className="h-4 w-4 text-pink-600" />
                        <span>Gender</span>
                      </label>
                      <select value={gender} onChange={(e) => setGender(e.target.value)} className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-pink-400 focus:border-transparent transition-all bg-gray-50 hover:bg-gray-100 text-gray-800" required>
                        <option value="" disabled>Select gender</option> <option value="male">Male</option> <option value="female">Female</option> <option value="other">Other</option> <option value="prefer-not-to-say">Prefer not to say</option>
                      </select>
                    </div>
                    {/* Hair Type Selection */}
                    <div className="space-y-2">
                      <label className="flex items-center space-x-2 text-sm font-semibold text-gray-700">
                        <Sun className="h-4 w-4 text-pink-600" /> <span>Hair Type</span>
                      </label>
                      <select value={hairType} onChange={(e) => setHairType(e.target.value)} className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-pink-400 focus:border-transparent transition-all bg-gray-50 hover:bg-gray-100 text-gray-800" required>
                        <option value="" disabled>Select hair type</option> <option value="straight">Straight</option> <option value="wavy">Wavy</option> <option value="curly">Curly</option> <option value="coily">Coily</option> <option value="fine">Fine</option> <option value="thick">Thick</option> <option value="damaged">Damaged</option> <option value="color-treated">Color-treated</option> <option value="unknown">Unknown / Not Sure</option>
                      </select>
                    </div>
                  </div>
                </div>

                {/* Photo Upload Section */}
                <div className="space-y-4 pt-4">
                  <div className="text-center">
                    <label className="flex items-center justify-center text-lg font-semibold text-gray-800 mb-2">
                      <Camera className="h-5 w-5 mr-2 text-pink-500" /> Upload a Photo of Your Hair/Scalp
                    </label>
                    <p className="text-gray-500 text-sm"> Include scalp if possible...</p>
                  </div>
                  {/* Upload box */}
                  <div className="relative w-full h-64 border-2 border-dashed border-gray-300 rounded-2xl flex items-center justify-center cursor-pointer transition-all duration-300 hover:border-pink-400 hover:bg-orange-50/50 group bg-gray-50">
                    <input type="file" accept="image/*" onChange={handleFileChange} className="absolute inset-0 w-full h-full opacity-0 cursor-pointer" id="hair-upload" required />
                    {preview ? (<div className="relative w-full h-full rounded-2xl overflow-hidden"> <img src={preview} alt="Hair scan preview" className="w-full h-full object-cover" /> <button type="button" onClick={removePhoto} className="absolute top-3 right-3 bg-red-500 hover:bg-red-600 text-white rounded-full p-2 shadow-lg transition-all duration-200 hover:scale-110"> <X className="h-4 w-4" /> </button> </div>)
                      : (<label htmlFor="hair-upload" className="cursor-pointer text-center text-gray-400 group-hover:text-orange-500 transition-colors p-6"> <Camera className="h-12 w-12 mx-auto mb-3 group-hover:scale-110 transition-transform" /> <p className="text-base font-medium mb-1">Click or drag file</p> <p className="text-sm">PNG, JPG, up to 10MB</p> </label>)}
                  </div>
                </div>

                {/* Submit & Reset Buttons */}
                <div className="flex flex-col sm:flex-row gap-4 pt-2">
                  <button type="submit" disabled={isAnalyzing || uploadingToCloudinary} className={`w-full flex-1 bg-gradient-to-r from-pink-500 to-red-500 hover:from-pink-600 hover:to-red-600 disabled:from-gray-400 disabled:to-gray-500 text-white font-bold py-4 px-6 rounded-xl transition-all duration-300 hover:scale-105 hover:shadow-xl disabled:opacity-70 disabled:cursor-not-allowed disabled:hover:scale-100 disabled:hover:shadow-none flex items-center justify-center space-x-2`}>
                    {isAnalyzing || uploadingToCloudinary ? (<> <Loader2 className="h-5 w-5 mr-2 animate-spin" /> <span> {uploadingToCloudinary ? 'Uploading...' : 'Analyzing...'} </span> </>)
                      : (<> <Sparkles className="h-5 w-5 mr-2" /> <span>Analyze Hair</span> </>)}
                  </button>
                  <button type="button" onClick={resetForm} className="px-8 py-4 bg-gray-200 hover:bg-gray-300 text-gray-800 font-medium rounded-xl transition-all duration-300 hover:scale-105"> Reset Form </button>
                </div>
              </form>
            </div> {/* End Left Side */}

            {/* Right Side - Analysis Results */}
            {analysisResult && (
              <div className="bg-white rounded-3xl shadow-xl p-8 border border-gray-100 animate-slideIn">
                {/* Header Section */}
                <div className="flex items-center justify-between mb-6">
                  <div className="flex items-center">
                    <div className="bg-gradient-to-r from-pink-500 to-red-500 p-3 rounded-xl mr-3"> <Sparkles className="h-6 w-6 text-white" /> </div>
                    <h2 className="text-2xl font-bold bg-gradient-to-r from-amber-600 via-pink-600 to-red-600 bg-clip-text text-transparent"> Hair Analysis Results </h2>
                  </div>
                  <div className="flex space-x-2">
                    <button onClick={downloadAnalysis} className="bg-gradient-to-r from-green-500 to-emerald-500 hover:from-green-600 hover:to-emerald-600 text-white px-4 py-2 rounded-xl flex items-center space-x-2 transition-all duration-300 hover:scale-105 shadow-lg" title="Download Analysis Report"> <Download className="h-4 w-4" /> <span className="hidden sm:inline">Download</span> </button>
                    <button onClick={() => navigate('/history')} className="bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600 text-white px-4 py-2 rounded-xl flex items-center space-x-2 transition-all duration-300 hover:scale-105 shadow-lg" title="View Analysis History"> <History className="h-4 w-4" /> <span className="hidden sm:inline">History</span> </button>
                  </div>
                </div>

                {/* Analysis Text Box - USING ORIGINAL STYLING */}
                {/* Container matching the NEW layout structure */}
                <div className="rounded-xl border border-gray-200 max-h-[calc(100vh-320px)] overflow-y-auto">
                  {/* Styling from ORIGINAL HairScan result box */}
                  <div className="bg-gradient-to-r from-amber-600 to-pink-600  text-white p-6">
                    <div className="prose prose-invert prose-sm max-w-none">
                      <div className="whitespace-pre-wrap leading-relaxed"> {/* Removed text-sm */}
                        {analysisResult}
                      </div>
                    </div>
                  </div>
                </div>

                {/* Analysis Metadata */}
                {currentAnalysisId && (
                  <div className="mt-4 p-3 bg-orange-50 border border-orange-200 rounded-xl">
                    <div className="flex items-center text-sm text-orange-700">
                      <div className="bg-orange-500 p-1 rounded-full mr-2"> <svg className="w-3 h-3 text-white" fill="currentColor" viewBox="0 0 20 20"> <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" /> </svg> </div>
                      <span>Analysis saved • ID: {currentAnalysisId.slice(-8)}</span>
                    </div>
                  </div>
                )}

                {/* Disclaimer Box */}
                <div className="mt-4 p-4 bg-yellow-50 border border-yellow-300 rounded-xl">
                  <div className="flex items-start">
                    <div className="bg-yellow-400 p-2 rounded-lg mr-3 mt-0.5"> <svg className="w-4 h-4 text-white" fill="currentColor" viewBox="0 0 20 20"> <path fillRule="evenodd" d="M8.257 3.099c..." clipRule="evenodd" /> </svg> </div>
                    <div>
                      <p className="font-semibold text-yellow-800 text-sm mb-1">Important Disclaimer</p>
                      <p className="text-yellow-700 text-sm"> This AI analysis is for informational purposes only... </p>
                    </div>
                  </div>
                </div>

              </div> // End Right Side
            )}
          </div> {/* End Grid */}
        </div>
      </div>

      {/* Style block copied from SkinScan */}
      <style>{`
        @keyframes float { 0%, 100% { transform: translateY(0px); } 50% { transform: translateY(-20px); } }
        @keyframes float-reverse { 0%, 100% { transform: translateY(0px); } 50% { transform: translateY(20px); } }
        @keyframes float-slow { 0%, 100% { transform: translateY(0px) scale(1); } 50% { transform: translateY(-15px) scale(1.05); } }
        @keyframes slideUp { from { transform: translateY(10px); opacity: 0; } to { transform: translateY(0); opacity: 1; } }
        @keyframes slideIn { from { transform: translateX(20px); opacity: 0; } to { transform: translateX(0); opacity: 1; } }
        .animate-float { animation: float 6s ease-in-out infinite; }
        .animate-float-reverse { animation: float-reverse 8s ease-in-out infinite; }
        .animate-float-slow { animation: float-slow 10s ease-in-out infinite; }
        .animate-slideUp { animation: slideUp 0.3s ease-out; }
        .animate-slideIn { animation: slideIn 0.4s ease-out; }
        .animation-delay-1000 { animation-delay: 1s; }
        /* Ensure prose styles apply correctly */
        .prose :where(h1,h2,h3,h4,strong):not(:where([class~="not-prose"] *)) { color: inherit; }
        .prose :where(ul > li::marker):not(:where([class~="not-prose"] *)) { color: var(--tw-prose-body); }
      `}</style>
    </div>
  );
};

export default HairScan;