import React, { useState, useEffect } from 'react';

import { Camera, User, Baby, Sun, X, Sparkles, Download, History, Loader2 } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { uploadToCloudinary } from './cloudinary';
import { saveSkinAnalysis } from './firestoreService';
import { auth } from './firebase';
import { onAuthStateChanged } from 'firebase/auth';


// The main component for the skin scan upload page.
const SkinScan = () => {

  const navigate = useNavigate();
  const [age, setAge] = useState('');
  const [gender, setGender] = useState('');
  const [skinType, setSkinType] = useState('');
  const [file, setFile] = useState(null);
  const [preview, setPreview] = useState(null);
  const [message, setMessage] = useState({ text: '', type: '' });
  const [isLoaded, setIsLoaded] = useState(false);
  const [analysisResult, setAnalysisResult] = useState(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [currentUser, setCurrentUser] = useState(null);
  const [uploadingToCloudinary, setUploadingToCloudinary] = useState(false);
  const [currentAnalysisId, setCurrentAnalysisId] = useState(null);

  
  useEffect(() => {
    setIsLoaded(true);

    // Listen for auth state changes
    const unsubscribe = onAuthStateChanged(auth, (user) => {
      setCurrentUser(user);
    });

    return () => unsubscribe();
  }, []);

  
  const showMessage = (text, type) => {
    setMessage({ text, type });
    setTimeout(() => {
      setMessage({ text: '', type: '' });
    }, 3000); // Message disappears after 3 seconds
  };

  const removePhoto = () => {
    setFile(null);
    if (preview) {
      URL.revokeObjectURL(preview);
    }
    setPreview(null);
    showMessage('Photo removed successfully', 'success');
  };

  const handleAgeChange = (e) => {
    const value = e.target.value;
    if (value === '' || (parseInt(value) >= 1 && parseInt(value) <= 120)) {
      setAge(value);
    } else if (parseInt(value) < 1) {
      showMessage('Age must be at least 1 year', 'error');
    }
  };

  const handleFileChange = (event) => {
    const selectedFile = event.target.files[0];
    if (selectedFile) {
      setFile(selectedFile);
      // Create a URL for the image preview.
      setPreview(URL.createObjectURL(selectedFile));
      showMessage('Photo uploaded successfully!', 'success');
    }
  };

  const fileToBase64 = (file) => {
    return new Promise((resolve, reject) => {
      const reader = new window.FileReader();
      reader.onload = () => resolve(reader.result.split(',')[1]);
      reader.onerror = reject;
      reader.readAsDataURL(file);
    });
  };

  const downloadAnalysis = () => {
    if (!analysisResult) return;

    const analysisText = `
SKIN ANALYSIS REPORT
=====================

Date: ${new Date().toLocaleDateString()}
Time: ${new Date().toLocaleTimeString()}

USER DETAILS:
- Age: ${age} years
- Gender: ${gender}
- Skin Type: ${skinType}

AI ANALYSIS:
${analysisResult}

---
Generated by GlowNexa AI Skin Analysis
This analysis is for informational purposes only and should not replace professional medical consultation.
    `;

    const blob = new Blob([analysisText], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `skin-analysis-${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);

    showMessage('Analysis downloaded successfully!', 'success');
  };

 
  const handleSubmit = async (event) => {

    event.preventDefault();

    if (parseInt(age) < 1) {
      showMessage('Age must be at least 1 year', 'error');
      return;
    }

    if (!file) {
      showMessage('Please upload a photo.', 'error');
      return;
    }

    if (!currentUser) {
      showMessage('Please log in to continue.', 'error');
      return;
    }

    setIsAnalyzing(true);
    setAnalysisResult(null);
    setCurrentAnalysisId(null);

    try {
      // Step 1: Upload image to Cloudinary
      showMessage('Uploading image to cloud storage...', 'success');
      setUploadingToCloudinary(true);

      const cloudinaryResult = await uploadToCloudinary(file);
      setUploadingToCloudinary(false);

      if (!cloudinaryResult.success) {
        throw new Error(`Image upload failed: ${cloudinaryResult.error}`);
      }

      showMessage('Image uploaded successfully! Analyzing with AI...', 'success');

      // Step 2: Convert image to base64 for Gemini API
      const imageBase64 = await fileToBase64(file);

      // Step 3: Call Gemini API for analysis
      const apiKey = process.env.REACT_APP_GEMINI_API_KEY;
     
      const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`;

      // Prepare comprehensive prompt for Gemini
      const prompt = `As a dermatology AI assistant, please analyze this skin image for the following user:

User Details:
- Age: ${age} years
- Gender: ${gender}
- Skin Type: ${skinType}

Please provide a comprehensive analysis in the following format:

1. SKIN CONDITION ASSESSMENT:
   - Overall skin condition
   - Any visible concerns or abnormalities
   - Skin texture and appearance

2. POTENTIAL ISSUES IDENTIFIED:
   - List any potential skin problems visible
   - Severity level (mild/moderate/severe)
   - Areas of concern

3. RECOMMENDATIONS:
   - Skincare routine suggestions
   - Ingredients to look for
   - Ingredients to avoid

4. LIFESTYLE TIPS:
   - Diet recommendations
   - Sleep and stress management
   - Environmental factors to consider

5. WHEN TO CONSULT A DERMATOLOGIST:
   - Warning signs to watch for
   - Recommended follow-up timeline

Please provide practical, actionable advice while emphasizing that this analysis is for informational purposes only and should not replace professional medical consultation.`;

      // Prepare request body with correct format for Gemini 1.5
      const body = {
        contents: [{
          parts: [
            { text: prompt },
            {
              inline_data: {
                mime_type: file.type,
                data: imageBase64
              }
            }
          ]
        }],
        generationConfig: {
          temperature: 0.4,
          topK: 32,
          topP: 1,
          maxOutputTokens: 4096,
        },
        safetySettings: [
          {
            category: "HARM_CATEGORY_HARASSMENT",
            threshold: "BLOCK_MEDIUM_AND_ABOVE"
          },
          {
            category: "HARM_CATEGORY_HATE_SPEECH",
            threshold: "BLOCK_MEDIUM_AND_ABOVE"
          },
          {
            category: "HARM_CATEGORY_SEXUALLY_EXPLICIT",
            threshold: "BLOCK_MEDIUM_AND_ABOVE"
          },
          {
            category: "HARM_CATEGORY_DANGEROUS_CONTENT",
            threshold: "BLOCK_MEDIUM_AND_ABOVE"
          }
        ]
      };

      const response = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body)
      });

      if (!response.ok) {
        const errorData = await response.json();
        console.error('API Error:', errorData);
        throw new Error(`API request failed: ${response.status} - ${errorData.error?.message || 'Unknown error'}`);
      }

      const data = await response.json();
      console.log('API Response:', data);

      const resultText = data?.candidates?.[0]?.content?.parts?.[0]?.text || 'No analysis could be generated. Please try again with a clearer image.';

      setAnalysisResult(resultText);
      showMessage('AI analysis complete! Saving to your profile...', 'success');

      // Step 4: Save analysis data to Firestore
      const analysisData = {
        age: parseInt(age),
        gender: gender,
        skinType: skinType,
        originalFileName: file.name,
        cloudinaryUrl: cloudinaryResult.url,
        cloudinaryPublicId: cloudinaryResult.public_id,
        prompt: prompt,
        aiResponse: resultText
      };

      const saveResult = await saveSkinAnalysis(currentUser.uid, analysisData);

      if (saveResult.success) {
        setCurrentAnalysisId(saveResult.analysisId);
        showMessage('Analysis saved successfully to your profile!', 'success');
      } else {
        console.error('Failed to save analysis:', saveResult.error);
        showMessage('Analysis complete, but failed to save to profile.', 'error');
      }

    } catch (error) {
      console.error('Analysis error:', error);
      setAnalysisResult(null);
      showMessage(`Failed to analyze: ${error.message}. Please try again.`, 'error');
    } finally {
      setIsAnalyzing(false);
      setUploadingToCloudinary(false);
    }
  };


  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-purple-50 to-pink-50">
      {/* Subtle animated background elements */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div className="absolute top-20 left-10 w-32 h-32 bg-blue-200/20 rounded-full blur-3xl animate-float"></div>
        <div className="absolute top-40 right-20 w-40 h-40 bg-purple-200/20 rounded-full blur-3xl animate-float-reverse"></div>
        <div className="absolute bottom-20 left-32 w-36 h-36 bg-pink-200/20 rounded-full blur-3xl animate-float-slow"></div>
        <Sparkles className="absolute top-32 right-1/4 h-6 w-6 text-purple-300/40 animate-pulse" />
        <Sparkles className="absolute bottom-1/3 left-1/4 h-5 w-5 text-blue-300/40 animate-pulse animation-delay-1000" />
      </div>

      {/* Main Content */}
      <div className={`relative z-10 min-h-screen p-6 flex items-start justify-center transition-all duration-1000 ${isLoaded ? 'opacity-100' : 'opacity-0'}`}>
        <div className="w-full max-w-7xl">
          {/* Header */}
          <div className="text-center mb-8 pt-6">
            <h1 className="text-5xl font-bold bg-gradient-to-r from-blue-600 via-purple-600 to-pink-600 bg-clip-text text-transparent mb-3">
              Upload Your Skin Scan
            </h1>
            <p className="text-gray-600 text-lg">
              Get AI-powered skin analysis with personalized recommendations
            </p>
          </div>

          <div className={`grid ${analysisResult ? 'lg:grid-cols-2' : 'lg:grid-cols-1 max-w-3xl mx-auto'} gap-6`}>
            {/* Left Side - Input Form */}
            <div className="bg-white rounded-3xl shadow-xl p-8 border border-gray-100">
              <div className="space-y-6">
                {/* User Details */}
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                  <div className="space-y-2">
                    <label htmlFor="age" className="flex items-center text-gray-700 font-medium text-sm">
                      <Baby className="h-4 w-4 mr-2 text-blue-500" /> Age
                    </label>
                    <input
                      type="number"
                      id="age"
                      value={age}
                      onChange={handleAgeChange}
                      placeholder="e.g., 30"
                      min="1"
                      max="120"
                      className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-blue-400 focus:border-transparent transition-all bg-gray-50 hover:bg-gray-100 text-gray-800 placeholder-gray-400"
                      required
                    />
                  </div>

                  <div className="space-y-2">
                    <label htmlFor="gender" className="flex items-center text-gray-700 font-medium text-sm">
                      <User className="h-4 w-4 mr-2 text-purple-500" /> Gender
                    </label>
                    <select
                      id="gender"
                      value={gender}
                      onChange={(e) => setGender(e.target.value)}
                      className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-purple-400 focus:border-transparent transition-all bg-gray-50 hover:bg-gray-100 text-gray-800"
                      required
                    >
                      <option value="" disabled>Select gender</option>
                      <option value="male" className="text-gray-800">Male</option>
                      <option value="female" className="text-gray-800">Female</option>
                      <option value="other" className="text-gray-800">Other</option>
                      <option value="prefer-not-to-say" className="text-gray-800">Prefer not to say</option>
                    </select>
                  </div>

                  <div className="space-y-2">
                    <label htmlFor="skinType" className="flex items-center text-gray-700 font-medium text-sm">
                      <Sun className="h-4 w-4 mr-2 text-pink-500" /> Skin Type
                    </label>
                    <select
                      id="skinType"
                      value={skinType}
                      onChange={(e) => setSkinType(e.target.value)}
                      className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-pink-400 focus:border-transparent transition-all bg-gray-50 hover:bg-gray-100 text-gray-800"
                      required
                    >
                      <option value="" disabled>Select skin type</option>
                      <option value="normal" className="text-gray-800">Normal</option>
                      <option value="oily" className="text-gray-800">Oily</option>
                      <option value="dry" className="text-gray-800">Dry</option>
                      <option value="combination" className="text-gray-800">Combination</option>
                      <option value="sensitive" className="text-gray-800">Sensitive</option>
                    </select>
                  </div>
                </div>

                {/* Photo Upload */}
                <div className="space-y-4 pt-4">
                  <div className="text-center">
                    <label className="flex items-center justify-center text-lg font-semibold text-gray-800 mb-2">
                      <Camera className="h-5 w-5 mr-2 text-blue-500" /> Upload a Photo of Your Skin
                    </label>
                    <p className="text-gray-500 text-sm">
                      For best results, ensure good lighting and clear image quality
                    </p>
                  </div>

                  <div className="relative w-full h-64 border-2 border-dashed border-gray-300 rounded-2xl flex items-center justify-center cursor-pointer transition-all duration-300 hover:border-blue-400 hover:bg-blue-50/50 group bg-gray-50">
                    <input
                      type="file"
                      accept="image/*"
                      onChange={handleFileChange}
                      className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
                      required
                    />
                    {preview ? (
                      <div className="relative w-full h-full rounded-2xl overflow-hidden">
                        <img
                          src={preview}
                          alt="Skin scan preview"
                          className="w-full h-full object-cover"
                        />
                        <button
                          type="button"
                          onClick={removePhoto}
                          className="absolute top-3 right-3 bg-red-500 hover:bg-red-600 text-white rounded-full p-2 shadow-lg transition-all duration-200 hover:scale-110"
                        >
                          <X className="h-4 w-4" />
                        </button>
                      </div>
                    ) : (
                      <div className="text-center text-gray-400 group-hover:text-blue-500 transition-colors p-6">
                        <Camera className="h-12 w-12 mx-auto mb-3 group-hover:scale-110 transition-transform" />
                        <p className="text-base font-medium mb-1">Click or drag a file to upload</p>
                        <p className="text-sm">PNG, JPG, up to 10MB</p>
                      </div>
                    )}
                  </div>
                </div>

                {/* Submit Button */}
                <button
                  type="button" // Type change to "button" to prevent default form submission
                  onClick={handleSubmit} 
                  disabled={isAnalyzing}
                  className={`w-full bg-gradient-to-r from-blue-500 via-purple-500 to-pink-500 text-white font-semibold py-4 px-6 rounded-xl shadow-lg transition-all duration-300 ${isAnalyzing
                      ? 'opacity-70 cursor-not-allowed'
                      : 'hover:shadow-xl hover:scale-[1.02] active:scale-[0.98]'
                    }`}
                >
                  <div className="flex items-center justify-center">
                    {isAnalyzing ? (
                      <>
                        <Loader2 className="h-5 w-5 mr-2 animate-spin" />
                        {uploadingToCloudinary ? 'Uploading image...' : 'Analyzing with AI...'}
                      </>
                    ) : (
                      <>
                        <Camera className="h-5 w-5 mr-2" />
                        Analyze My Skin
                      </>
                    )}
                  </div>
                </button>

                {/* Message */}
                {message.text && (
                  <div
                    className={`p-4 rounded-xl font-medium border-l-4 animate-slideUp ${message.type === 'success'
                        ? 'bg-green-50 text-green-700 border-green-500'
                        : 'bg-red-50 text-red-700 border-red-500'
                      }`}
                  >
                    <div className="flex items-center">
                      <div className={`w-2 h-2 rounded-full mr-3 ${message.type === 'success' ? 'bg-green-500' : 'bg-red-500'
                        }`}></div>
                      {message.text}
                    </div>
                  </div>
                )}
              </div>
            </div>

            {/* Right Side - Analysis Results */}
            {analysisResult && (
              <div className="bg-white rounded-3xl shadow-xl p-8 border border-gray-100 animate-slideIn">
                <div className="flex items-center justify-between mb-6">
                  <div className="flex items-center">
                    <div className="bg-gradient-to-r from-blue-500 to-purple-500 p-3 rounded-xl mr-3">
                      <Sparkles className="h-6 w-6 text-white" />
                    </div>
                    <h2 className="text-2xl font-bold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
                      AI Skin Analysis & Recommendations
                    </h2>
                  </div>

                  <div className="flex space-x-2">
                    <button
                      onClick={downloadAnalysis}
                      className="bg-gradient-to-r from-green-500 to-emerald-500 hover:from-green-600 hover:to-emerald-600 text-white px-4 py-2 rounded-xl flex items-center space-x-2 transition-all duration-300 hover:scale-105 shadow-lg"
                      title="Download Analysis Report"
                    >
                      <Download className="h-4 w-4" />
                      <span className="hidden sm:inline">Download</span>
                    </button>

                
                    <button
                      onClick={() => navigate('/history')}
                      className="bg-gradient-to-r from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600 text-white px-4 py-2 rounded-xl flex items-center space-x-2 transition-all duration-300 hover:scale-105 shadow-lg"
                      title="View Analysis History"
                    >
                      <History className="h-4 w-4" />
                      <span className="hidden sm:inline">History</span>
                    </button>
                  </div>
                </div>

                <div className="bg-gradient-to-br from-blue-50 to-purple-50 rounded-xl p-6 border border-gray-200 max-h-[calc(100vh-320px)] overflow-y-auto">
                  <div className="prose prose-sm max-w-none">
                    <div
                      className="whitespace-pre-line text-lg leading-relaxed text-gray-800"
                      style={{
                        fontFamily: 'system-ui, -apple-system, sans-serif',
                        lineHeight: '1.8'
                      }}
                    >
                      {analysisResult}
                    </div>
                  </div>
                </div>

                {/* Analysis Metadata */}
                {currentAnalysisId && (
                  <div className="mt-4 p-3 bg-blue-50 border border-blue-200 rounded-xl">
                    <div className="flex items-center text-sm text-blue-700">
                      <div className="bg-blue-500 p-1 rounded-full mr-2">
                        <svg className="w-3 h-3 text-white" fill="currentColor" viewBox="0 0 20 20">
                          <path fillRule="evenodd" d="M16.707 5.293a1 1 0 010 1.414l-8 8a1 1 0 01-1.414 0l-4-4a1 1 0 011.414-1.414L8 12.586l7.293-7.293a1 1 0 011.414 0z" clipRule="evenodd" />
                        </svg>
                      </div>
                      {/* Text color changed to match new UI (blue-700) */}
                      <span>Analysis saved to your profile • Analysis ID: {currentAnalysisId.slice(-8)}</span>
                    </div>
                  </div>
                )}

                <div className="mt-4 p-4 bg-yellow-50 border border-yellow-300 rounded-xl">
                  <div className="flex items-start">
                    <div className="bg-yellow-400 p-2 rounded-lg mr-3 mt-0.5">
                      <svg className="w-4 h-4 text-white" fill="currentColor" viewBox="0 0 20 20">
                        <path fillRule="evenodd" d="M8.257 3.099c.765-1.36 2.722-1.36 3.486 0l5.58 9.92c.75 1.334-.213 2.98-1.742 2.98H4.42c-1.53 0-2.493-1.646-1.743-2.98l5.58-9.92zM11 13a1 1 0 11-2 0 1 1 0 012 0zm-1-8a1 1 0 00-1 1v3a1 1 0 002 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
                      </svg>
                    </div>
                    <div>
                      {/* Text color changed to match new UI (yellow-800 / yellow-700) */}
                      <p className="font-semibold text-yellow-800 text-sm mb-1">Important Disclaimer</p>
                      <p className="text-yellow-700 text-sm">
                        This AI analysis is for informational purposes only and should not replace professional medical advice.
                        Please consult a qualified dermatologist for proper diagnosis and treatment.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

      
      <style>{`
        @keyframes float {
          0%, 100% { transform: translateY(0px); }
          50% { transform: translateY(-20px); }
        }
        
        @keyframes float-reverse {
          0%, 100% { transform: translateY(0px); }
          50% { transform: translateY(20px); }
        }
        
        @keyframes float-slow {
          0%, 100% { transform: translateY(0px) scale(1); }
          50% { transform: translateY(-15px) scale(1.05); }
        }
        
        @keyframes slideUp {
          from { transform: translateY(10px); opacity: 0; }
          to { transform: translateY(0); opacity: 1; }
        }
        
        @keyframes slideIn {
          from { transform: translateX(20px); opacity: 0; }
          to { transform: translateX(0); opacity: 1; }
        }
        
        .animate-float { animation: float 6s ease-in-out infinite; }
        .animate-float-reverse { animation: float-reverse 8s ease-in-out infinite; }
        .animate-float-slow { animation: float-slow 10s ease-in-out infinite; }
        .animate-slideUp { animation: slideUp 0.3s ease-out; }
        .animate-slideIn { animation: slideIn 0.4s ease-out; }
        .animation-delay-1000 { animation-delay: 1s; }
      `}</style>
    </div>
  );
};

export default SkinScan;